import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createServer } from 'vite'

const OUT_DIR = 'supabase/functions/_shared'
const ICS_SRC = 'src/data/calendarIcs.ts'
const ICS_CORE_OUT = `${OUT_DIR}/calendar-ics.core.generated.ts`

const ICS_CORE_TYPES = `/** Minimal event shape used by ICS / Google schedule helpers (Deno-safe). */
export type CalendarEventKind =
  | 'holiday'
  | 'event'
  | 'timetable'
  | 'progress'
  | 'department'
  | 'assessment'
  | 'school-day'
  | 'non-school-day'

export type CalendarEvent = {
  id: string
  date: string
  title: string
  kind: CalendarEventKind | string
  createdBy?: string
  audience?: {
    type: string
    ownerId?: string
    teacherIds?: string[]
    grades?: number[]
    subjects?: string[]
  }
  schoolYearStart?: number
  time?: { start: string; end: string }
  lesson?: {
    group: string
    subject: string
    start: string
    end: string
    room?: string
  }
}
`

/**
 * Emit a Deno-friendly copy of the pure ICS helpers from src/data/calendarIcs.ts.
 * Edge wrappers in calendar-ics.ts add updatedAt / SEQUENCE / REFRESH-INTERVAL.
 */
function emitCalendarIcsCore() {
  const raw = readFileSync(ICS_SRC, 'utf8')

  // Drop the Vite/React types import — replace with a local structural type.
  let body = raw.replace(
    /^import type \{ CalendarEvent, CalendarEventKind \} from '\.\.\/types'\n\n/m,
    '',
  )

  // Frontend-only URL helpers — not needed on the edge.
  body = body.replace(
    /\nexport function feedUrlFromToken[\s\S]*$/m,
    '\n',
  )

  // Edge buildIcsCalendar reuses escaping; export the helper.
  body = body.replace(/^function escapeIcs\(/m, 'export function escapeIcs(')

  const out = `/** GENERATED — do not edit.
 * Source: ${ICS_SRC}
 * Regenerated by: npm run export:calendar-bundle
 */

${ICS_CORE_TYPES}
${body}`

  writeFileSync(ICS_CORE_OUT, out, 'utf8')
  console.log(`Wrote ${ICS_CORE_OUT}`)
}

async function main() {
  emitCalendarIcsCore()

  const server = await createServer({ server: { middlewareMode: true } })
  try {
    const calendarEvents = await server.ssrLoadModule('/src/data/calendarEvents.ts')
    const whitelist = await server.ssrLoadModule('/src/data/teacherWhitelist.ts')
    const staff = await server.ssrLoadModule('/src/data/staffUsers.ts')

    const { buildSeedCalendarEvents } = calendarEvents as {
      buildSeedCalendarEvents: () => unknown[]
    }
    const {
      TEACHER_WHITELIST_2526,
      TEACHER_WHITELIST_2627,
      latestTeacherWhitelistYear,
      teacherUserIdFromInitial,
    } = whitelist as {
      TEACHER_WHITELIST_2526: Array<{
        initial: string
        name: string
        email: string
        classes: string[]
      }>
      TEACHER_WHITELIST_2627: Array<{
        initial: string
        name: string
        email: string
        classes: string[]
      }>
      latestTeacherWhitelistYear: () => number
      teacherUserIdFromInitial: (initial: string) => string
    }
    const { ADMIN_INITIALS } = staff as {
      ADMIN_INITIALS: readonly string[]
    }

    const mapWhitelist = (
      rows: Array<{
        initial: string
        name: string
        email: string
        classes: string[]
      }>,
    ) =>
      rows.map((t) => ({
        userId: teacherUserIdFromInitial(t.initial),
        initial: t.initial,
        name: t.name,
        email: t.email,
        classes: t.classes,
      }))

    const adminUserIds = [
      'u-admin',
      ...ADMIN_INITIALS.map((initial) => teacherUserIdFromInitial(initial)),
    ]

    const bundle = {
      seed: buildSeedCalendarEvents(),
      whitelistByYear: {
        2025: mapWhitelist(TEACHER_WHITELIST_2526),
        2026: mapWhitelist(TEACHER_WHITELIST_2627),
      },
      latestWhitelistYear: latestTeacherWhitelistYear(),
      adminUserIds,
    }

    mkdirSync(OUT_DIR, { recursive: true })
    writeFileSync(
      `${OUT_DIR}/calendar-bundle.json`,
      JSON.stringify(bundle),
      'utf8',
    )
    console.log(
      `Wrote ${(bundle.seed as unknown[]).length} seed events to ${OUT_DIR}/calendar-bundle.json`,
    )
  } finally {
    await server.close()
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
